### ISSUE TITLE
-l operator at the end doesn't work

### ISSUE THREAD

**Issue by jbaylina** [iden3/circom#109]
If the -l parameter (include dir) is at the last parameter it doesn't work. If it's at the first one it does.

Example:

This doesn't work:

 ~/git/zkevm/pil-stark/ [main*] circom --wasm --sym --r1cs --output outdir --prime goldilocks --O1 -l circuits.gl circuit.circom
invalid input file
previous errors were found

But this does:
 ~/git/zkevm/pil-stark/ [main*] circom --wasm -l circuits.gl --sym --r1cs --output outdir --prime goldilocks --O1 circuit.circom

**Comment by miguelis** [comment]
Fixed! Now, we allow multiple appearances of option -l but each of these must only have one value.

(Previously, since circuit.circom was right after option -l, it was interpreted as another value for the option instead of the input.)
