### ISSUE TITLE
circom takes forever to compile a circuit

### ISSUE THREAD

**Issue by hellwolf** [iden3/circom#12]
Following your example at: https://iden3.io/blog/circom-and-snarkjs-tutorial.html

Version: circom@0.0.17
Nodejs: v8.12.0
Machine: ubuntu 18.04

```
$ cat multiplier.circom 
template Multiplier() {
    signal private input a;
    signal private input b;
    signal output c;

    c <== a*b;
}

component main = Multiplier();

$ npx circom multiplier.circom -o multiplier.circom 
```

The compilation didn't finish in 5 minutes...

**Comment by hellwolf** [comment]
1 #!/usr/bin/env node --max_old_space_size=4000

from ./node_modules/.bin/circom seems the culprit, why the max_old_space_size flag anyways?

**Comment by hellwolf** [comment]
Removing the --max_old_space_size=4000 flag made it work for me.

**Comment by hellwolf** [comment]
I started to use node10, but I had to remove that flag still otherwise simple examples wouldn't run.

**Comment by weijiekoh** [comment]
Sorry to hear that. One way to get around this quickly is to not use the `circom` CLI, but write a separate JS script that imports `circom`, compiles the circuit, and saves the json output. That'll let you compile it without having to modify `cli.js`. Hope that helps as a quick workaround.

**Comment by jbaylina** [comment]
Ok, this depends probably too much in the memory you have in your device.  I just updated to remove the --max_old_space_size=4000 flag from cli.js.  

I'll take a look if I can optimize a little the memory usage....

**Comment by hellwolf** [comment]
Thanks!
