### ISSUE TITLE
Circom should not forcibly exit on success

### ISSUE THREAD

**Issue by phated** [iden3/circom#122]
In https://github.com/iden3/circom/commit/b953bf92df54004373a4049e29f0e160a5a57486, @miguelis made circom forcibly exit on success, which makes many workflows (such as using the circom tool inside a script or when using it in WASM) break. It would probably be fine to forcibly exit with a code if there is an **error** but never should you forcibly exit with `0` on a success.

I tried removing the exit and circom hits an `unreachable` in the code, so more fixes will need to be applied to make the code work correctly.

**Comment by phated** [comment]
I submitted https://github.com/antimatter15/circom/pull/12 as a workaround for this problem, which completely broke hardhat-circom (ref https://github.com/projectsophon/hardhat-circom/issues/72)

**Comment by miguelis** [comment]
@phated  Hey Blaine. Do u have the code which hits unreachable in the code? I want to execute it and find the bug to check everything is ok when we are returning 0.

**Comment by phated** [comment]
@miguelis I believe it was happening with this simple division circuit in circom-starter: https://github.com/0xPARC/circom-starter/blob/master/circuits/division.circom

**Comment by miguelis** [comment]
Can you check it again please? I didn't got any unreachable compiling that file. 
Thanks!

**Comment by phated** [comment]
@miguelis do you have a branch where you remove the `exit(0)` call?

**Comment by xavi-pinsach** [comment]
@phated `no_exit_with_0` branch
