### ISSUE TITLE
is there any tool or method to boost the speed of proof generation for very large circuit?

### ISSUE THREAD

**Issue by xichan-ms** [iden3/circom#123]
as the title, I'd like to know if there is any tool or method, such as GPU or parallel computing? thanks a lot

**Comment by OBrezhniev** [comment]
Hi @xichan-ms! You can try our very efficient CPU prover [iden3/rapidsnark](https://github.com/iden3/rapidsnark) if you haven't yet. Otherwise a better place to ask is [iden3 chat](https://t.me/iden3io) in telegram.
