### ISSUE TITLE
Segmentation fault when generating witness with C++

### ISSUE THREAD

**Issue by JSedlmeir92** [iden3/circom#127]
When using the ecdsa_verify circuit from https://github.com/personaelabs/efficient-zk-sig and a slight modification thereof that avoids nested JSONs to make it compatible with ark-circom, I noticed that witness generation with C++ aborts with a segmentation fault, while WASM-based witness generation works just fine. I traced the problem down to where the release_memory_component in CheckCarryToZero_22_run in circuit_cpp/circuit.cpp is called. In the telegram channel, I was told that release_memory_component was only added recently, so probably this is the issue. When the release_memory_component is not called from CheckCarryToZero_22, the witness is generated successfully.

A minimal example to recreate the issue can be found at https://github.com/JSedlmeir92/circomCWtnsGenBugExample. Thank you for keeping up the great work on circom!

**Comment by clararod9** [comment]
Hello,

Thank you for reporting the bug and giving so many details about the issue, it was really helpful!
I think that the last commit fixes the behavior of the function release_memory_component (it failed when a template had an array of subcomponents with some empty positions).
