### ISSUE TITLE
Public Signals

### ISSUE THREAD

**Issue by crashpilot** [iden3/circom#130]
Hey!

I have written a zk-circuit that works perfectly fine when all input signals are set to default/private.
However, if I want to change the visibility of 1-2 signals to public the zkey generation takes around 10  min (instead of the previous 30s).
`component main {public [a,b]}= SomeCircuit();`

Further, I can no longer generate ZK proofs with help of the snarkjs implementation.
Currently I use the following command:
`const { proof, publicSignals } = await snarkjs.plonk.fullProve(inputs, "circuit.wasm", "circuit_final.zkey");`

As said, with all signals set to private it works perfectly fine, if I set some to public I get the following error:
"Uncaught (in promise) TypeError: Failed to fetch"

Since I use circom and snarkjs as part of my master thesis I would appreciate any fast answer :)

Edit:
My circuit has around 75k constraints and I use powersOfTau28_hez_final_18.ptau for the zkey generation.

Edit2:
An update from circom 2.0.7 to 2.1.2 and from snarkjs 0.4.24 to 0.5.0 did NOT fix the issue.

Best Regards,
Crashpilot

**Comment by miguelis** [comment]
Can you make accessible the code?

**Comment by crashpilot** [comment]
Sure, here is the full code:
```
pragma circom 2.1.2;

include "../node_modules/circomlib/circuits/eddsamimc.circom";
include "../node_modules/circomlib/circuits/eddsa.circom";
include "../node_modules/circomlib/circuits/pointbits.circom";
include "../node_modules/circomlib/circuits/bitify.circom";


template VerifyReview(){
    // all inputs are already in bit representation
    signal input A_sig1[256]; // public key point A = (x,y), with x and y being 128 bits long each
    signal input R8_sig1[256]; // Signature consists of R and S, with R being a point and S a scalar
    signal input S_sig1[256];

    signal input A_sig2[256];
    signal input R8_sig2[256];
    signal input S_sig2[256];

    signal input M1[512]; // H(pseudoynm) + H(realID)
    signal input M2[512]; // H(productID) + H(realID)

    signal input review[1024]; // H(rating) + H(reviewText) + H(productID) + H(pseudonym)

    signal input realId[256]; // 256 bit realID; Secret Key
    signal input tag[256]; // H(H(productID) + realID))

    var i;

    log("Start of Circuit");

    log("Start of Sanity Checks");
    for (i=0; i<256; i++) { // Sanity Checks
        M1[256+i] === M2[256+i];
        M1[i] === review[768+i];
        M2[i] === review[512+i];
    }
    log("End of Sanity Checks");
    


    component verifier1 = EdDSAVerifier(512);
    component verifier2 = EdDSAVerifier(512);
    log("Start of Init EdDSAVerifier");
    for (i=0; i<256; i++) {
        verifier1.A[i] <== A_sig1[i];
        verifier1.R8[i] <== R8_sig1[i];
        verifier1.S[i] <== S_sig1[i];

        verifier2.A[i] <== A_sig2[i];
        verifier2.R8[i] <== R8_sig2[i];
        verifier2.S[i] <== S_sig2[i];
    }
    log("End of Init EdDSAVerifier");


    component hashTag = Pedersen(512);
    for (i=0;i<256;i++) {
        hashTag.in[i] <== M2[i];
        hashTag.in[256+i] <== realId[i];
    }

    component point2bits = Point2Bits_Strict();
    point2bits.in[0] <== hashTag.out[0];
    point2bits.in[1] <== hashTag.out[1];


    for (i=0;i<256;i++) {
        point2bits.out[i] === tag[i];
    }

    log("verifier msg input");    
    for ( i=0; i<512; i++) {
        verifier1.msg[i] <== M1[i];
        verifier2.msg[i] <== M2[i];
    }
}

// component main {public [review,tag]}= VerifyEdDSA();
component main = VerifyReview();```

**Comment by miguelis** [comment]
@crashpilot I compiled your code and checked that both the R1CS and WASM file are very similar (with some differences because of the public signals). So, I think the problem you have is related to snarkjs. You should open an issue in its github with the code you pasted here to see what is happening.
