### ISSUE TITLE
Sum of quadratic constraints is not a quadratic constraint

### ISSUE THREAD

**Issue by Dimo99** [iden3/circom#131]
I am creating a small circuit where I want to sum quadratic constraints. Unfortunately, I get the following error.
Why is that so?
```
var sum = 0;

  for (var i = 0; i < choices; i ++) {
      eqs[i] = IsEqual();
      eqs[i].in[0] <== i;
      eqs[i].in[1] <== index;

      sum += eqs[i].out * array[i];
  }

  out <== sum;
```

```
error[T3001]: Non quadratic constraints are not allowed!
   ┌─ "circuits/indexing.circom":27:3
   │
27 │   out <== sum;
   │   ^^^^^^^^^^^ found here
   │
   = call trace:
     ->Indexing

previous errors were foun
```

**Comment by miguelis** [comment]
Variable sum contains the addition of all quadratic constraints, yes. However, circom works with a particular kind of quadratic constraints (R1CS format). They have the shape A*B - C = 0. Then, if we unfold the meaning of sum, 
it would be something like out === eqs[0].out * array[0] + eqs[1].out * array[1] + ... + ens[n-1].out * array[n-1], which is not a R1CS constraint.

**Comment by trangnv** [comment]
Hey, 
just digging up the treasure here. What is the solution that you came up here?
