### ISSUE TITLE
Wrong Circuit Output from Modular Multiplication

### ISSUE THREAD

**Issue by darth-cy** [iden3/circom#132]
A simple circuit that squares the input is written as below:

```jsx
pragma circom 2.0.0;

template Square () {
    signal input _i;
    signal output h;

    h <== _i * _i;
}

component main = Square();
```

Value of prime P is determined according to [Circom Basic Operator page](https://docs.circom.io/circom-language/basic-operators/) documentation. The modular operator should be applied automatically. 

A zk verification setup from [SnarkJS](https://github.com/iden3/snarkjs) was followed with Groth16 paradigm. Ptau and zkey files are all verified as OK. A proof was generated with the command:

```jsx
> snarkjs groth16 fullprove input.json circuit.wasm circuit_final.zkey proof.json public.json
```

input.json:

```jsx
{
    "_i": 28265289914350957453642680820395460745145800835532716398271986448227478599675
}
```

public.json (which contains the circuit output):

```jsx
[
 "11851208546046643110441296205740735734806434337265558945270393801559197064892"
]
```

### Verify Using Solidity 0.8.17 (in Remix)

The same routine is coded as a smart contract as:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

contract Hasher {
    uint256 P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function square(uint256 _i) public view returns (uint256 h) {
        h = mulmod(_i, _i, P);
    }
}
```

which outputs:
<img width="706" alt="Screenshot 2022-11-22 at 2 08 55 AM" src="https://user-images.githubusercontent.com/4976777/203248825-7b88dd40-07e4-4637-88c8-ee95d6f91d6d.png">

---

### Verify Using Python

The same routine was implemented with the following code:

```jsx
# square.py

p = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
_i = 28265289914350957453642680820395460745145800835532716398271986448227478599675;

r = (_i * _i) % p;
print(r);
```

which outputs:

```jsx
> 17193533575592330193369691401356841215361251320429544254322836094031795527997
```

---

*Please instruct on how the Circom circuit can be implemented to output the same value as Solidity. Thank you!*

**Comment by miguelis** [comment]
You can check in the [documentation](https://docs.circom.io/getting-started/computing-the-witness/#what-is-a-witness):
"We need to create a file named input.json containing the inputs written in the standard json format.
We use strings instead of numbers because JavaScript does not work accurately with integers larger than 2^53."

I have checked that when using the corresponding string, then you get the expected public value.
