### ISSUE TITLE
Illegal instruction in cpp

### ISSUE THREAD

**Issue by zkh2016** [iden3/circom#134]
matElemMul.circom:
```
pragma circom 2.0.0;

// matrix multiplication by element
template matElemMul (m,n) {
    signal input a[m][n];
    signal input b[m][n];
    signal output out[m][n];
    
    for (var i=0; i < m; i++) {
        for (var j=0; j < n; j++) {
            out[i][j] <== a[i][j] * b[i][j];
        }
    }
}
component main = matElemMul(4,4);
```
I use the `--c` option to compile, but when I compute the witness in cpp, I prompt "illegal instruction". 
So how to use it correctly?

env:
```
ubuntu 18.04
gcc 6.5.0 
```

**Comment by alrubio** [comment]
I tried your code and it works without error. Can you detail all the steps you followed and the input data you are using?
