### ISSUE TITLE
docs:: Poor Render of first bracket

### ISSUE THREAD

**Issue by abhik-wil** [iden3/circom#137]
In the `mkdocs/docs/background/background.md` file the following is rendered on Github:

![In Github](https://user-images.githubusercontent.com/106070541/210736929-a86a6687-78e3-41c5-be6a-2fc9396e9508.png)

But on the Site [here](https://docs.circom.io/background/background/#_1:~:text=circuit%20must%20satisfy.-,Rank,-%2D1%20constraint%20system) it renders as:

![as Rendered](https://user-images.githubusercontent.com/106070541/210737144-b0087cf7-bb49-4861-a9f6-c38a72b338b7.png)

Note how the text within first bracket becomes differently formatted on the site. Is this a problem on the mkdocs side? There are no problems in the Github Markdown.

**Comment by miguelis** [comment]
Thanks, merged!
