### ISSUE TITLE
Compiling time difference resulted from signal namings.

### ISSUE THREAD

**Issue by katat** [iden3/circom#141]
Any ideas on the potential causes of [this issue](https://github.com/zk-email-verify/zk-regex/issues/2)?

**Comment by alrubio** [comment]
Thanks for reporting. This can be related to the simplification phase, which is a costly process that uses some heuristics that can be affected by the order in which signals are treated. In general, signal names does not affect the process but component names may affect it. Can you provide us with the full circom circuit? I tried to download them from the git but the files cannot be compiled.
If so we can see what's happening.

**Comment by katat** [comment]
Thanks for the hints.

It does seem to be raised from the implications phrase. So here are the two circom files with one different component variable name. When the component name is `check_matched_start` as is in `slower.compiled.circom.txt` file, it is around 6min slower. 

[faster.compiled.circom.txt](https://github.com/iden3/circom/files/10670943/compiled.circom.txt)
[slower.compiled.circom.txt](https://github.com/iden3/circom/files/10670946/slower.compiled.circom.txt)

Also, when I use the circom CLI with `--O0` parameters, the compilation is fast. But I don't what is the trade-off to turn off the simplification phrase. It would be nice to understand the purpose of the simplification phrase and how it works. 

I also attached the other circuits. But keep in mind it also uses `circomlib`.
[regex_helpers.circom.txt](https://github.com/iden3/circom/files/10671006/regex_helpers.circom.txt)
[test_regex_compiler.circom.txt](https://github.com/iden3/circom/files/10670997/test_regex_compiler.circom.txt)

**Comment by katat** [comment]
Yeah, so I benchmark it, and without simplification is slower in calculating witness but faster in compilation.

**Comment by alrubio** [comment]
The problem has been solved in the last release. Now the compilation time is similar. Thanks again for reporting.
