### ISSUE TITLE
log() doesn't work inside functions

### ISSUE THREAD

**Issue by ArshanKhanifar** [iden3/circom#143]
`log` doesn't seem to print inside functions, here's a really small example: 
```
pragma circom 2.0.6

function print(a) {
    log("helloooo");
    return 1;
}

template Main() {
    signal input a;
    log("before");
    var c = print(a);
    log("after", c);
}

component main {public[a]} = Main();
```
with the input (I just made up a value) : 
```
{"a": 20}
```
running this produces this output: 
```
before
after 1
```

Doing computations inside the function does work however. 
Not sure if this was an intended use case haha.

**Comment by clararod9** [comment]
Hi! Thank you for reporting the issue :-)

The issue only affected to functions returning constant values. We have solved this problem in our last release v2.1.5, and now the behavior is the expected: 

`before
helloooo
after 1
`

 Let us know if the current solution is working for you
