### ISSUE TITLE
Strange behaviour with constraints and arithmetic

### ISSUE THREAD

**Issue by weijiekoh** [iden3/circom#15]
Given this input:

```
{ i: 4, j: 4 }
```

This circuit is invalid:
```
template X() {
    signal input i;
    signal input j;
    signal output out;

    var r = 0;
    for (var n=0; n<i; n++) {
        r++;
    }

    i === r;
    out <== r;
}

component main = X();
```

So is this:

```
    out <-- r;
    out === i;
```

Also invalid:

```
    r === i;
    out <== r;
```

And this:

```
    r - 4 === 0;
    out <== r;
```

But this is valid:

```
    out <-- i/r;
    out === 1;
```

**Comment by weijiekoh** [comment]
Anyone reading this, try:

```
i  * i === i * r;
```

It may have to do with the following information in the README:

> The constraint must be simplificable to a constraint of the form `a*b+c=0`, where `a`, `b` and `c` are linear combinations of the signals.

**Comment by jbaylina** [comment]
Now it works.

**Comment by weijiekoh** [comment]
Thanks for the fixes!
