### ISSUE TITLE
Compiler panic when assigning a slice to a tag

### ISSUE THREAD

**Issue by tjade273** [iden3/circom#151]
This causes a panic 

```
template Main(){
    signal {tag} s;
    s.tag = [1,2];
}
component main = Main();
```

```
thread 'main' panicked at 'assertion failed: memory_slice.is_single()', /Users/tjaden/circom/program_structure/src/utils/memory_slice.rs:326:9
```

due to unwrapping the `[1,2]` as a single expression.

https://github.com/iden3/circom/blob/ca3345681549c859af1f3f42128e53e3e43fe5e2/constraint_generation/src/execute.rs#L884

It would be nice if this were supported, but until then it should give a clear error.

**Comment by clararod9** [comment]
Hi!

In the new release (version 2.1.5) we handle this case and produce an error message indicating that the tags expect single elements, not slices.

``` 
error[T2000]: Typing error found
  ┌─ "falla.circom":4:5
  │
4 │     s.tag = [1,2];
  │     ^^^^^^^^^^^^^ Assignee and assigned types do not match. 
 Expected dimensions: 0, found 1

previous errors were found
``` 

In future versions of the compiler we will consider your recommendation of allowing the assignments of slices to tags.

Thank you for reporting the issue!
