### ISSUE TITLE
Is assert built into the constraint?

### ISSUE THREAD

**Issue by ClankPan** [iden3/circom#157]
Hi, I'm learning zk-snark at cricom.

In [this article](https://kunalm.xyz/posts/zksnark-battleship.html) they use `assert` to check the condition. Is `assert` included in the constraint?

**Comment by alrubio** [comment]
No, asserts are not included in the constraint system. 
The only constraints that are added in this example are a * b - d = 0 and c + d - out = 0 (although the second one, as it is linear, might be simplified depending on the optimization applied). 
Asserts that depend on signals (like in the example) are only included as checks in the wasm or C++ code that computes the witness from the inputs, so when they fail the witness computation is aborted. 
If an assert only depends on known information like template parameters its is checked at compile time and if it fails compilation is aborted and an error message is shown.
If you want to add what is written in the asserts as constraints you can use the template IsZero from the circomlib/circuits/comparators.circom (that should be added with an include) with a code like this:
signal a1 <== IsZero()(a-1);
signal b1 <== IsZero()(b-1);
a1 === 0;
b1 === 0;
Note that e.g. a1 === 0; introduces a constraint in the r1cs and a check (a1 == 0) in the witness generation wasm or C++ code. So the asserts in the original code are not needed.
