### ISSUE TITLE
How can i change the prime number p in the circom language?

### ISSUE THREAD

**Issue by goodbye1998** [iden3/circom#159]
[**Circom 2 Documentation**](https://docs.circom.io/circom-language/basic-operators/) introduces that the circom language is parametric to the number (p = 21888242871839275222246405745257275088548364400416034343698204186575808495617), and it can be changed without affecting the rest of the language (using **GLOBAL_FIELD_P**). But I don't know how to set the parameter **GLOBAL_FIELD_P**.
It seems that the default **GLOBAL_FIELD_P** is for **BabyJubJub** elliptic curve. How can I modify **GLOBAL_FIELD_P** to fit other curves (Such as the G1 group in BN256)?

**Comment by alrubio** [comment]
Currently you can only use three primes (using the --prime flag). See https://docs.circom.io/getting-started/compilation-options/ for more details.
In the future we will add more primes and even allow user defined primes.
