### ISSUE TITLE
documentation of newer features is not accessible from the table of content

### ISSUE THREAD

**Issue by bkomuves** [iden3/circom#166]
I accidentally learned that newer circom versions have new features like signal tags.

However the documentation page for signal tags: https://docs.circom.io/circom-language/tags/ (and some others) are not accessible while browsing the documentation pages (only from the search feature, if you already know what to search for).

**Comment by clararod9** [comment]
Hi! 
Thank you for reporting this issue, we have solved it in our last commit :-)

**Comment by bkomuves** [comment]
thanks!
