### ISSUE TITLE
Formal language specification

### ISSUE THREAD

**Issue by tim-hoffman** [iden3/circom#178]
Is there a formal specification of the language available anywhere? I'm looking for a complete specification of the syntax and semantics of Circom. I've read https://docs.circom.io/circom-language/signals/ but it is not comprehensive. Thanks!

**Comment by miguelis** [comment]
There is not an available formal circom semantics. There are a few papers presenting circom, but for more information, the best you can find is in the documentation you already have. However, if you have found some imprecisions in the documento, let us know and we will try to clarify them. Thanks!
