### ISSUE TITLE
Typo in circuits/sha256

### ISSUE THREAD

**Issue by Doresimon** [iden3/circom#20]
in /sha256/main.js

~include "sha256_2.jaz";~
include "sha256_2.circom";

~component sha256_2 = SHA256_2();~
component sha256_2 = Sha256_2();

And when I run 
$> node cli.js circuits/sha256/main.circom -o sha256.json
the node ran for about 10 minutes and met 'heap out of memory'

Did I use the right method?

**Comment by Doresimon** [comment]
My pc has 16GB memory...

**Comment by weijiekoh** [comment]
Run it this way:

```
node --max-old-space-size=4000 .................
```
