### ISSUE TITLE
Circom outputs to incorrect paths

### ISSUE THREAD

**Issue by TheFrozenFire** [iden3/circom#21]
I've been chasing this issue for a while now, trying to figure out why circom_tester is failing when I'm using temp files for circuits. For some reason, circom is removing a portion of the base file name, and circom_tester assumes a given file name.

### Test steps:
* `echo "pragma circom 2.0.0; template foo () {} component main = foo();" > /tmp/test2021104-13814-o1so8j.x9v4k.circom`
* `circom --wasm --sym --r1cs --output $(mktemp -d) /tmp/test2021104-13814-o1so8j.x9v4k.circom`

*Note the input file name, which is a format that common temp file generation libraries use (in this case node-temp)*

### Expected:
```
template instances: 1
non-linear constraints: 0
linear constraints: 0
public inputs: 0
public outputs: 0
private inputs: 0
private outputs: 0
wires: 1
labels: 1
Written successfully: /tmp/tmp.xvLoOJQNqm/test2021104-13814-o1so8j.x9v4k.r1cs
Written successfully: /tmp/tmp.xvLoOJQNqm/test2021104-13814-o1so8j.x9v4k.sym
Written successfully: /tmp/tmp.xvLoOJQNqm/test2021104-13814-o1so8j.x9v4k_js/test2021104-13814-o1so8j.x9v4k.wasm
Everything went okay, circom safe
```

### Actual:
```
template instances: 1
non-linear constraints: 0
linear constraints: 0
public inputs: 0
public outputs: 0
private inputs: 0
private outputs: 0
wires: 1
labels: 1
Written successfully: /tmp/tmp.xvLoOJQNqm/test2021104-13814-o1so8j.r1cs
Written successfully: /tmp/tmp.xvLoOJQNqm/test2021104-13814-o1so8j.sym
Written successfully: /tmp/tmp.xvLoOJQNqm/test2021104-13814-o1so8j.x9v4k_js/test2021104-13814-o1so8j.wasm
Everything went okay, circom safe
```

**Comment by TheFrozenFire** [comment]
I may have been using an older build of circom when this occurred. When I switched from debug to release build, this issue went away. Closing for now.

**Comment by TheFrozenFire** [comment]
Initially I had given two examples of this issue, but the first one resolved after rebuilding circom from a fresh working copy. I had closed the issue assuming that both issues resolved, but one case still remains.

**Comment by alrubio** [comment]
I've answered you to the PR.

**Comment by alrubio** [comment]
We have fixed the bug changing the build_output function. Thanks for pointing out the problem.
