### ISSUE TITLE
cpp witness generation illegal instruction Fr_rawMMul

### ISSUE THREAD

**Issue by rickardomc** [iden3/circom#229]
multiplier2.circom (I also tried with another example proposed on the circom documentation):
```
pragma circom 2.0.0;

template Multiplier2() {
    signal input a;
    signal input b;
    signal output c;
    c <== a*b;
 }

component main = Multiplier2();
```
commands: 
```
circom multiplier2.circom --c
cd multiplier2_cpp
#create input.json as {"a":"3", "b":"11"}
make
./multipler2 input.json witness.wtns
```
gdb error:
```
Program received signal SIGILL, Illegal instruction.
0x000055555555c91b in Fr_rawMMul ()
```
env:
```
OS: ubuntu 20.04.6LTS 64bit
processor: Intel® Core™ i5-4440 CPU @ 3.10GHz × 4 
gcc: 9.4.0
GMP: 6.2.0
nasm: 2.14.02-1
nlohmann-json3-dev 3.7.3-1
```

**Comment by visopsys** [comment]
I got exactly the same problem. The witness generation fails on Intel based CPU but succeeds on AMD (both using Ubuntu 22).

Extra libs that I installed on: `build-essential libgmp-dev libsodium-dev nasm nlohmann-json3-dev libssl-dev zlib1g-dev`. I think these are libs needed for either compiling c++ or snarkjs.

**Comment by visopsys** [comment]
Both of my machines are using Ubuntu 22. 

I am trying to install different OS version on the machine that fails. Will let you know the result.

**Comment by OBrezhniev** [comment]
Hello @rickardomc @visopsys! You need processor with the support of ADX instructions (Intel Broadwell from 2014 and newer). i5-4440 is older Haswell microarchitecture, which doesn't have it.

**Comment by visopsys** [comment]
Thanks @OBrezhniev . This makes sense. The server that fails uses intel xeon e5-1650v3 chip which is based on Haswell architecture.
