### ISSUE TITLE
Operator reference does not define `<==` operator

### ISSUE THREAD

**Issue by matthiasgeihs** [iden3/circom#232]
Hey, I'm making myself familiar with circom and was going through the [operators reference documentation](https://github.com/iden3/circom/blob/master/mkdocs/docs/circom-language/basic-operators.md).

I was quite surprised to not find any explicit information about the seemingly fundamental `<==` operator.

**Comment by miguelis** [comment]
Thanks for the observation. We have included an explanation for the <== and <-- operators in [signals](https://github.com/iden3/circom/blob/master/mkdocs/docs/circom-language/signals.md) section.
