### ISSUE TITLE
Implementing exponential circuit in circom

### ISSUE THREAD

**Issue by vaibhavsingh1993** [iden3/circom#25]
Hi,
I was playing around with circom and snarkjs, and am confused about the circom circuit for exponents.
Seems like something of the form:
` 
 out <== input_a**input_b;
`
throws the error:
`TypeError: Cannot read property 'value' of undefined`

I am not sure if that is expected.
Also, if this is expected, is there a different way to implement an exponent circuit in circom?

**Comment by jbaylina** [comment]
Exponents can only be used in assignmets. `r <-- a**b`  The double arrow implies a constraint and this can only be a quadratic expression.
