### ISSUE TITLE
Require a better error message on unknown dimensions

### ISSUE THREAD

**Issue by genfengDog** [iden3/circom#27]
https://github.com/iden3/circom/blob/7e59274c3e78674c2178766f9b8a4371c760ac3a/constraint_generation/src/execute.rs#L160

Got a panic on this kind of code. (I forget to give a value to N). Maybe a better error message is required.

```
    var N;
    signal input in[N];
```

![image](https://user-images.githubusercontent.com/5971517/145995834-4e7d086d-d564-4470-9d93-69d7cb82f624.png)

**Comment by alrubio** [comment]
A message "Array dimension with unknown size" is now shown. Please, update to get it fixed.
Thanks for reporting it.
