### ISSUE TITLE
Docs: Undefined {**} operator

### ISSUE THREAD

**Issue by dsernst** [iden3/circom#276]
https://docs.circom.io/circom-language/basic-operators/

<img width="704" alt="image" src="https://github.com/user-attachments/assets/c63fb6e6-f65e-4d85-a039-e0b69e07a99c">

*Ctrl+F `{**}` on that page linked above*

------

Part way down the page, `{**}` gets used twice, and then never mentioned again.

`**` is defined (as exponentiation), but the `{` and `}` braces are not (at least not anywhere else on that page).

Unclear if it has a special meaning, or is just meant to help disambiguate nested parens, or specifying order of operations, or what exactly.

**Comment by dsernst** [comment]
Permalink to relevant markdown file: https://github.com/iden3/circom/blob/9f3da35a8ac3107190f8c85c8cf3ea1a0f8780a4/mkdocs/docs/circom-language/basic-operators.md?plain=1#L108-L110

**Comment by miguelis** [comment]
Brackets must be removed from the documentation since they do not mean anything. Solved! Thanks
