### ISSUE TITLE
[about license] used in closed-source commercial software

### ISSUE THREAD

**Issue by tjchern** [iden3/circom#278]
In my closed-source commercial software, can I use your software directly by depending on it?
This circom code itself is not modified.
thanks

**Comment by Arvolear** [comment]
[Generally speaking](https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60), the GPLv3 license allows usage in closed-source, commercial software, as long as the source code remains unmodified. Circom is [released](https://github.com/iden3/circom/blob/master/COPYING) under GPLv3, so you shouldn't face any problems with that.

**Comment by OBrezhniev** [comment]
Hello! 

Answer depends on the way of using GPLv3 licensed software.

@Arvolear your answer is incorrect generally speaking.

@tjchern, @Arvolear please see these articles:
https://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem
https://en.wikipedia.org/wiki/GNU_General_Public_License#Use_of_licensed_software
https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

**Comment by Arvolear** [comment]
Licensing is a deep rabbit hole.

I mean if the Circom compiler is used as a compiler for building proprietary circuits / applications, the GPL license should allow that.

Otherwise if one is building some compiler wrapper, then the wrapper must be GPL licensed as well.
