### ISSUE TITLE
Different Results for Complement Bitwise Operator of Zero

### ISSUE THREAD

**Issue by LukiMueller** [iden3/circom#283]
This issue is a follow up to #270.

I can confirm that for some bit-wise `~` expressions the computation result is now as expected.
However, there are still instances where the evaluation seems to produce the wrong result:

**circuit.circom**
~~~
pragma circom 2.1.9;

template T() {

    signal a;
    signal b;

    signal zero;
    zero <-- 0;

    a <-- (~ 0);
    b <-- (~ zero);

    log("a = ", a);
    log("b = ", b);
}

component main = T();
~~~

**output**
~~~
a =  0
b =  7059779437489773633646340506914701874769131765994106666166191815402473914366
~~~

**Comment by miguelis** [comment]
Solved thanks!
