### ISSUE TITLE
MiMC compression function construct

### ISSUE THREAD

**Issue by fredlacs** [iden3/circom#29]
Hey there! Really cool project you've got going on here.
Been playing around with the library lately and noticed some differences in the MiMC implementation compared to ethsnarks'. I made an issue there and got a great answer 
https://github.com/HarryR/ethsnarks/issues/119. 

The MiMC implementation from @HarryR uses a different compression function, compared to circom's. I believe that circom's team can give a much better answer than me with regards to which one is more appropriate! The whole ecosystem can benefit from some standardisation :)

**Comment by jbaylina** [comment]
Answered in the other thread: https://github.com/HarryR/ethsnarks/issues/119#issuecomment-485234095
