### ISSUE TITLE
Integer division template

### ISSUE THREAD

**Issue by chaosma** [iden3/circom#35]
Is it possible to do integer division in circom? For example, something like this would be great:

```
pragma circom 2.0.0;

function div(a, b) {
    var r = a;
    var q = 0;
    while (r >= b) {
        r = r - b;
        q = q + 1;
    }
    return q;
}

template test() {
    signal input a;
    signal input b;
    signal output c;
    c <== div(a, b);
}
component main = test();
```

It will not work because "non quadratic constraint" error. However, I tried other kinds of division algorithm, but still cannot remove such error.

**Comment by harshadptl** [comment]
Division constraints can be replaced by Multiplication ones.

**Comment by Aniruddha-Upadhya-K** [comment]
> Is it possible to do integer division in circom? For example, something like this would be great:
> 
> ```
> pragma circom 2.0.0;
> 
> function div(a, b) {
>     var r = a;
>     var q = 0;
>     while (r >= b) {
>         r = r - b;
>         q = q + 1;
>     }
>     return q;
> }
> 
> template test() {
>     signal input a;
>     signal input b;
>     signal output c;
>     c <== div(a, b);
> }
> component main = test();
> ```
> 
> It will not work because "non quadratic constraint" error. However, I tried other kinds of division algorithm, but still cannot remove such error.

Hi, @chaosma did you get the solution for the query because I'm stuck at same issue?
and @harshadptl it would be great if you could give more explanation as I want to perform integer division.
Thank you!
