### ISSUE TITLE
circom breaks when a multi-line comment is closed with **/

### ISSUE THREAD

**Issue by whyamiroot** [iden3/circom#37]
Having a multi-line comment closed with `**/` breaks circom, the errors shown may be misleading.

Working example:
```circom
pragma circom 2.0.0;
/*
*/
template test() {
    signal input in;
    signal output out;
    out <== in * 2;
}
component main = test();
```

An example to reproduce the issue:
```circom
pragma circom 2.0.0;
/*
**/
template test() {
    signal input in;
    signal output out;
    out <== in * 2;
}
component main = test();
```
In the example above, the displayed compilation error is `error[P1001]: No main specified in the project structure`. 

If a comment closed with `**/` happens to be inside a template, the compiler seems to think the comment was never closed.
```
error[P1000]: UnrecognizedEOF { location: 38, expected: ["\"!\"", "\"(\"", "\"-\"", "\"[\"", "\"assert\"", "\"component\"", "\"for\"", "\"if\"", "\"log\"", "\"return\"", "\"signal\"", "\"var\"", "\"while\"", "\"{\"", "\"}\"", "\"~\"", "r#\"0x[0-9A-Fa-f]*\"#", "r#\"[$_]*[a-zA-Z][a-zA-Z$_0-9]*\"#", "r#\"[0-9]+\"#"] }
  ┌─ "/home/whyamiroot/test.circom":1:1
  │
1 │ pragma circom 2.0.0;
  │ ^ Invalid syntax
```

Here's an example to reproduce the error message above:
```circom
pragma circom 2.0.0;
template test() {
    /*
    **/
    signal input in;
    signal output out;
    out <== in * 2;
}
```

Other conditions that I tried to trigger this issue:
- inline comment `/**/` - doesn't trigger
- inline comment `/***/` - triggers
- inline comment `// ...` - doesn't trigger with any combination of asterisks and slashes
- multiline comment with `/*`, `*`, and `*/` on separate lines - doesn't trigger

Environment:
- OS: Ubuntu 18.04
- cargo version: 1.58.0 (f01b232bc 2022-01-19)
- circom version: 2.0.3
- circom flags: `--r1cs --wasm --sym`

**Comment by alrubio** [comment]
Thanks for pointing it out. The problem was only with **/
Now, it is fixed. Please, update.
