### ISSUE TITLE
updating version of zksnark breaks test

### ISSUE THREAD

**Issue by jaym910** [iden3/circom#4]
Currently the package.json file imports zksnark@0.0.6, which no longer exists, so I updated package.json to import zksnark@0.0.10 (I also had to add yargs to package.json).

The CLI appears to be working so far, but it looks like the sha256 test fails now due to updating the zksnark lib. More specifically it looks like line 75 is causing the problem:
```javascript
assert(witness[1].equals(zkSnark.bigInt(r)));
```
where `const r` is a hex string.

**Comment by jbaylina** [comment]
zksnarks has moved to snarkjs.  Now the tests should work.
