### ISSUE TITLE
Illegal instruction: 4 for Mac M1 Chip

### ISSUE THREAD

**Issue by tianqiwuben** [iden3/circom#43]
I'm following the tutorials for the simple multiplier here.
[https://docs.circom.io/getting-started/computing-the-witness/](https://docs.circom.io/getting-started/computing-the-witness/)

The generated cpp files do not support arm64 by default. So I compiled everything using `arch -x86_64`. However when I run the compiled file to generate the witness, it gives me
```
$./multiplier2 input.json witness.wtns
Illegal instruction: 4
```

Please advise how to fix?
Thanks

**Comment by miguelis** [comment]
Exactly, there is a problem with the [Mac M1 Chip when using C++ to generate the witness](https://github.com/iden3/circom/issues/31). We will fix this problem in the future but in the meantime, you can try to generate the witness using WebAssembly instead of C++.

**Comment by nickz-t3** [comment]
why is this completed? where is the pr? the cpp code still does not work for arm architecture

**Comment by vdrg** [comment]
Running into the same issue right now @alrubio
