### ISSUE TITLE
How can I modify GLOBAL_FIELD_P in circom？

### ISSUE THREAD

**Issue by zhaolty** [iden3/circom#49]
Hi！I'm a novice about **circom**.
I want to modify **GLOBAL_FIELD_P**, but don't know how to do it.
Can someone help me with this problem with an example？This is important to my research.

**Comment by alrubio** [comment]
Currently you can't change it, as the generated code for wasm and C++ can only work with the given Prime number.
This might be added in future versions.

**Comment by alrubio** [comment]
I mean you can change it in the compiler.

**Comment by alrubio** [comment]
I mean you can't change it in the compiler
