### ISSUE TITLE
The --wasm option produces three JavaScript files?

### ISSUE THREAD

**Issue by nobutoba** [iden3/circom#52]
The ["Getting started"](https://docs.circom.io/getting-started/computing-the-witness/) part of the documentation says:

> Let us start with the Wasm code. Using the generated Wasm binary and ***three*** JavaScript files, we simply need to provide...
>
>&mdash;<https://github.com/iden3/circom/blob/master/mkdocs/docs/getting-started/computing-the-witness.md>

However, the command `circom multiplier2.circom --wasm` only produces ***two*** JavaScript files:

```bash
$ ls -1 multiplier2_js
generate_witness.js
multiplier2.wasm
witness_calculator.js
```

I would be happy if I could know this was simply a typo.

Just so you know, I'm using circom 2.0.4, and the full content of multiplier2.circom is the following.

```circom
pragma circom 2.0.4;

template Multiplier2() {
    signal input a;
    signal input b;
    signal output c;
    c <== a*b;
 }

 component main = Multiplier2();
```

**Comment by alrubio** [comment]
It is just a typo (in earlier implementations it was producing three). We will change it in the new release.
Thanks
