### ISSUE TITLE
A figure of an F_7-arithmetic circuit is missing

### ISSUE THREAD

**Issue by nobutoba** [iden3/circom#53]
The ["Background"](https://docs.circom.io/background/background/#signals-of-a-circuit) part of the documentation says:

> In the figure below, we have defined an `F_7`-arithmetic circuit that performs the operation...
>
> &mdash;<https://github.com/iden3/circom/blob/master/mkdocs/docs/background/background.md>

However, no image actually shows up. The reason is that the following link to the image is dead:
<https://gblobscdn.gitbook.com/assets%2F-MDt-cjMfCLyy351MraT%2F-MHR5icu-Jxuas-UC7DY%2F-MHR60RuAQK6qNzhOPgE%2Foutput.jpg?alt=media&token=39d3d332-cac5-4546-ab43-9f489241ae50>

**Comment by miguelis** [comment]
Thanks for the comment. Now you can check that the figure is shown.
