### ISSUE TITLE
Add version tags

### ISSUE THREAD

**Issue by apogiatzis** [iden3/circom#54]
It seems that the repository does not follow any version tagging strategy.

I believe adding version tags would be helpful for many users given that one may want to pin circom installation to specific a version in order to maintain compatibility with other dependencies. 

One example is performing circom installation through Docker.

**Comment by alrubio** [comment]
We have just added the tags. Let us know if it is as expected.

**Comment by apogiatzis** [comment]
> We have just added the tags. Let us know if it is as expected.

That's great! Much appreiated!
