### ISSUE TITLE
Require main to be defined - or at least warn about

### ISSUE THREAD

**Issue by hacera** [iden3/circom#6]
This is an improvement suggestion. While one can easily compile a template such as

```
template MyTemplate() {
    signal private input a;
    signal private input b;
    signal output c;

    c <== a*b;
}
```

That is, without defining the component `main`, such as
```
template MyTemplate() {
    signal private input a;
    signal private input b;
    signal output c;

    c <== a*b;
}
component main = MyTemplate();
```

It may be helpful to at the very least warn about it during compilation.

Thank you, Jonathan

**Comment by jbaylina** [comment]
Thank you for the contribution and for the incredible correction you made in the tutorial.

Just fixed on v0.0.15
