### ISSUE TITLE
[Question] Pass the array into and retrieve the array from a function

### ISSUE THREAD

**Issue by a2468834** [iden3/circom#8]
Hello everyone~ 😀

Recently, I'm writing circom version of my python functions.
(To make the zk proof of python functions' output)

If I have a python function, I can easily pass the array into and retrieve the array from that function.

```python
def myFunc(in_array):
    # Some calculations
    return out_array

if __name__ == "__main__":
    in_array = [1, 2, 3];
    out_array = myFunc(in_array);
```

However, according to [docs](https://docs.circom.io/circom-language/functions/), I cannot find examples or somewhere else that talking about passing array into a function.
Currently, I guess that it might be something like this:

```circom
function myFunc(in_array) {
    // Some calculations
    return out_array;
}

template mainFunc() {
	signal private input in_array; // A fixed length array
	signal private input b;
	signal output out;
	
	var out_array = myFunc(in_array);
}

component main = mainFunc();
```

Thanks for anyone willing to give me the answer or some clues about how I could develop in this situation. 🙏❤

**Comment by alrubio** [comment]
(1) Now it is fine, but you have to remove the "private" and "inter".
     Moreover , depending on what you do  temp could also be an array of var, as you had before.
(2) Sorry, you are right. I was confused with the out_array of the above template where it was an array of signals.
Since here it is an array of vars out_array[i] = c.out_array[i]; is ok
The weird thing in the second template is that you are not defining the value of the output signal.

**Comment by a2468834** [comment]
Wow, thanks for all of you are so accommodating and willing to give me a lot of helpful comments.👍❤
Here are some conclusions (no question anymore). I hope this could help other Circom newcomers.

---

(1) A very important rule!
> An array of signals should be assigned one by one.

(2) Functions vs templates
> Functions are only for calculating of things that **do not involve signals**.
> In your case, you should create a component using template instead of function.

(3) Some combinations and their validities about `signal`, `var`, `<==`, and `=`.
- `signal` is assigned by "<==" and can be assigned only once.
- `var` is assigned by "=".

``` circom
signal a;
signal b;

var var_a;
var var_b;

a <== 123;       // Valid
a <== b;         // Valid
a <== var_a;     // Valid

a = 123;         // Invalid, please use "<=="
a = b;           // Invalid, please use "<=="
a = var_a;       // Invalid, please use "<=="

var_a = 123;     // Valid
var_a = var_b;   // Valid
var_a = a;       // Valid

var_a <== 123;   // Invalid, please use "="
var_a <== a;     // Invalid, please use "="
var_a <== var_b; // Invalid, please use "="
```

(4) The revised pseudo-code which performs passing and retrieving array.
```circom
template foo(length) {
	signal input in_array_foo[length];
	signal temp[length]; // Store temporary results and can be assigned only once
	signal output out_array_foo[length];
	
	// Do something
	
	for(var i = 0; i<length; i++) {
		out_array_foo[i] <== temp[i];
	}
}

template mainFunc(length) {
	signal input in_array[length];
	signal output out_array[length];
	
	component bar = foo(length);
	
	// Pass input array
	for(var i = 0; i < length; i++) {
		bar.in_array_foo[i] <== in_array[i];
	}
	
	// Retrieve output array
	for(var i = 0; i < length; i++) {
		out_array[i] <== bar.out_array_foo[i];
	}
}

component main = mainFunc(NUMBER_DEFINED_STATICLY);
```
