### ISSUE TITLE
how to deal with this problem? "circom circuit.circom --r1cs --wasm --sym"

### ISSUE THREAD

**Issue by wzm397** [iden3/circom#96]
When I execute the command "circom circuit.circom --r1cs --wasm --sym", I get the following problem, what is it? How should I solve it?
![image](https://user-images.githubusercontent.com/61742432/183632715-36756c8c-0ca2-407d-960e-2526d8f8af06.png)

**Comment by alrubio** [comment]
Can you provide the code of circuit.circom?

**Comment by nalinbhardwaj** [comment]
This appears to be the same issue as https://github.com/iden3/circom/pull/57 @alrubio. I'd really appreciate if this can be fixed, many repositories which compiled with old versions of circom just fine break due to this issue.

**Comment by clararod9** [comment]
We fixed this issue in the version 2.1.1, thank you for reporting the bug :)
